analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/src/lang/class_utils.dart
    - lib/src/view/effect/hflip_transition.dart
    - lib/src/view/experimental/video/**