# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    sources:
      {"exclude" : ["bin/**"]}
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/material_buttons.dart
          - web/material_input.dart
          - web/material_radio.dart
          - web/playground_tests.dart
        dev_options:
          compiler: dartdevc
          ignore_cast_failures: true
        release_options:
          compiler: dart2js
          ignore_cast_failures: true
          dart2js_args:
            - --fast-startup
            - --minify
            - --trust-type-annotations
            # Consult https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
            # before enabling the following option:
         # - --trust-primitives