# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/material_buttons.dart
          - web/material_input.dart
          - web/material_radio.dart
        dev_options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
           # See https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
           # - --dump-info
           # - --fast-startup
            - --minify
            - --no-frequency-based-minification
            - --no-source-maps
            - --show-package-warnings
            - --trust-primitives
            - --trust-type-annotations