name: acanvas_commons
version: 0.11.0
author: Nils Döhring
description: UI Components, Event Bus, Command Queues and Helpers for Dart 2.0, StageXL, and Acanvas Framework.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: any
  stagexl: '>=1.4.0+1 <2.0.0'
dev_dependencies:
  build_runner: '>=0.10.0 <2.0.0'
  build_test: '>=0.10.2+5 <2.0.0'
  build_web_compilers: '>=0.4.0+4 <2.0.0'