name: stagexl_commons
version: 0.4.0
description: StageXL Commons consist of a port of as3commons and highly customizable View Components
dependencies:
  logging: any
  stagexl: 
    git : https://github.com/bp74/StageXL
dependency_overrides:
    stagexl:
      #git: https://github.com/bp74/StageXL
      path: /Users/ndoehring/Documents/WebstormProjects/StageXL
transformers:
- $dart2js:
    minify: true
    #verbose: true
    #commandLineOptions: [--dump-info]