name: stagexl_commons
version: 0.5.0
description: StageXL Commons consist of a port of as3commons and highly customizable View Components
dependencies:
  logging: any
  stagexl: 
    git : https://github.com/bp74/StageXL
# temporary override until StageXL accepts pull request
# https://github.com/bp74/StageXL/pull/212
dependency_overrides:
  stagexl:
    git : https://github.com/blockforest/StageXL
transformers:
- $dart2js:
    minify: true
    #verbose: true
    #commandLineOptions: [--dump-info]