name: stagexl_commons
version: 0.3.0
description: StageXL Commons consist of a port of as3commons and highly customizable View Components
dependencies:
  logging: any
  stagexl: 
    git : https://github.com/blockforest/StageXL
    #git : https://github.com/bp74/StageXL
transformers:
- $dart2js:
    minify: true
    #verbose: true
    #commandLineOptions: [--dump-info]