name: rockdot_commons
version: 0.6.1
description: Rockdot Commons consist of a port of as3commons and highly customizable View Components, including a Material Design implementation
dependencies:
  logging: any
  stagexl: any
transformers:
- $dart2js:
    minify: true
    #verbose: true
    #commandLineOptions: [--dump-info]